classdef TestSlm < otslm.utils.TestShowable
% Non-physical slm-like device for testing code.
% Inherits from :class:`TestShowable`.
%
% The ``showRaw`` function applies the inverse of the lookup table,
% converts from phase to a complex amplitude and assigns the result to the
% ``pattern`` property.
%
% Properties
%  - pattern (complex)  -- pattern generated by the ``showRaw`` method.
%    This pattern is the complex amplitude after multiplying by
%    the incident illumination and is the same size as the device.
%  - incident (complex) -- incident illumination.
%
% Constant properties
%  - size (size) -- device resolution in pixels [rows, columns]
%  - valueRange  -- range of raw device values (default: ``{0:255}``)
%  - patternType -- type of pattern for device (fixed: ``'phase'``)
%  - lookupTable -- Lookup table for the device.  Defaults to a linear
%    mapping of 0 to 2pi to the discrete colour levels of the device.
%
% See also TestSlm, :class:`TestDmd` and :class:`TestFarfield`.

% Copyright 2018 Isaac Lenton
% This file is part of OTSLM, see LICENSE.md for information about
% using/distributing this file.

  properties
    incident                % Incident illumination profile
  end

  properties (SetAccess=protected)
    pattern                 % Pattern currently displayed on the device
    
    valueRange              % Range of values for raw pattern
    lookupTable             % Lookup table for raw values
    patternType = 'phase';  % Type of pattern show() expects
  end
  
  properties (Dependent)
    size                    % Size of the device
  end

  methods

    function slm = TestSlm(varargin)
      % Create a new virtual SLM object for testing
      %
      % Usage
      %   slm = TestSlm(...) creates a device with a linear phase lookup
      %   table from 0 to 2*pi.
      %
      % Optional named arguments
      %   - size (size)          -- size of the device (``[rows, cols]``).
      %   - incident  (complex)  -- incident illumination
      %   - lookup_table         -- lookup table for colormap
      %   - value_range  (cell)  -- cell array with channel values for raw
      %     pattern.  Default: ``{0:255}``.  Use ``{0:255, 0:255, 0:255}``
      %     for three channel device with 256 levels on each channel.

      % Parse inputs
      p = inputParser;
      p.addParameter('lookup_table', []);
      p.addParameter('incident', []);
      p.addParameter('size', [512, 512]);
      p.addParameter('value_range', {0:255});
      p.parse(varargin{:});
      
      % Call base constructor
      slm = slm@otslm.utils.TestShowable();
      
      % Store value range and size
      slm.valueRange = p.Results.value_range;
      our_size = p.Results.size;
      
      % Default argument for incident
      if isempty(p.Results.incident)
        slm.incident = ones(our_size);
      else
        slm.incident = p.Results.incident;
      end
      
      % Default argument for lookup table
      slm.lookupTable = p.Results.lookup_table;
      if isempty(slm.lookupTable)
        value = slm.linearValueRange('structured', true).';
        phase = linspace(0, 2*pi, size(value, 1)).';
        slm.lookupTable = otslm.utils.LookupTable(...
            phase, value, 'range', 2*pi);
      end
      
      % Show the device, ensures pattern is initialized
      slm.show();
    end
    
    function showRaw(slm, pattern)
      % Simulate the pattern being shown, store result in obj.output
      
      % If no work, display a empty screen
      if nargin == 1
        pattern = zeros(slm.size);
      end
      
      % TODO: Support for multi-channel devices
      
      % Apply inverse lookupTable (colormap returns a normalized pattern)
      slm.pattern = otslm.tools.colormap(pattern, slm.lookupTable, 'inverse', true);
      
      % Convert colormap to complex amplitude
      slm.pattern = complex(exp(1i*2*pi*slm.pattern) .* slm.incident);
    end
    
    function set.incident(slm, newincident)
      % Check the new incident pattern
      assert(ismatrix(newincident), 'Incident pattern must be matrix');
      slm.incident = newincident;
    end
    
    function sz = get.size(slm)
      % Get the size of the device (i.e. the incident image)
      sz = size(slm.incident);
    end
  end

end
